services:
  db:
    image: postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: nest_api

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080